"use strict";
exports.__esModule = true;
var juridica_1 = require("../intidades/pj/juridica");
var fisica_1 = require("../intidades/pf/fisica");
var pedrosAcount = new fisica_1.fisicpeopleacount(12349590461, 'Pedro Lucas', 'pedro@email.com', 'Pedro', 0);
pedrosAcount.consultaomnt();
pedrosAcount.adicionarVaoramount(5000);
pedrosAcount.consultaomnt();
pedrosAcount.removeValueOfamount(1);
console.log(pedrosAcount.getAmount());
console.log(pedrosAcount.getNunberOfacount());
var newtabaconunt = new juridica_1.IJuridiquePeople(32159440916, 'Newtab Academy', 0);
newtabaconunt.consultaomnt();
newtabaconunt.adicionarVaoramount(5000);
newtabaconunt.consultaomnt();
newtabaconunt.removeValueOfamount(1);
console.log(newtabaconunt.getAmount());
console.log(newtabaconunt.getNunberOfacount());
console.log(newtabaconunt.getcnpj());
